<?php
/*
 *  Copyright © Websolute spa. All rights reserved.
 *  See COPYING.txt for license details.
 */

/** @var ViewModel $viewModel */

use Magento\Framework\View\Element\Template;
use Websolute\AttributeValueExtra\ViewModel\AttributeValueExtraSelect as ViewModel;

/** @var Template $block */
$viewModel = $block->getViewModel();

if ($viewModel->isEnabled()):?>
<script>
    require([
        'jquery',
        'mage/url'
    ], function ($, url) {
        window.murl = url;
        window.attributeValueExtra = {
            getAttributeList() {
                const entityTypeId = $('#entity-type-id').val();
                const data = {
                    'entity_type_id': entityTypeId
                }
                const url = "<?php echo $block->getUrl('*/*/getattributebyentitytypeajax') ?>";
                $.post( url, data, function (attributes) {
                    attributes.forEach(function (a) {
                        $('#attribute-id').append('' +
                            '<option value="'+ a.attribute_id +'">' +
                            a.attribute_code +
                            '</option>'
                        );
                    })

                }, "json" );
            },
            getAttributeValueList() {
                const entityTypeId = $('#entity-type-id').val();
                const attributeId = $('#attribute-id').val();
                const websiteId = $('#website-id').val();
                const storeGroupId = $('#store-group-id').val();
                const storeId = $('#store-id').val();
                const data = {
                    'entity_type_id': entityTypeId,
                    'website_id': websiteId,
                    'store_group_id': storeGroupId,
                    'store_id': storeId
                }
                const url = "<?php echo $block->getUrl('*/*/getattributevaluesajax') ?>";
                $.post( url, data, function (response) {
                    console.log(response);
                }, "json" );
            }
        }
    });
</script>
    <?php $entityTypeCodes = $viewModel->getEntityTypeCodes(); ?>
    <div class="attribute-list-container">
        <form>
            <input type="hidden" id="website-id" value="<?= $viewModel->getSwitcherWebsite(); ?>"/>
            <input type="hidden" id="store-group-id" value="<?= $viewModel->getSwitcherStoreGroup(); ?>"/>
            <input type="hidden" id="store-id" value="<?= $viewModel->getSwitcherStore(); ?>"/>
            <label for="entity-type-id">Entity Type:</label>
            <select id="entity-type-id" onchange="attributeValueExtra.getAttributeList()">
                <option name=" " value=" " selected="selected"> </option>
                <?php foreach ($entityTypeCodes as $entityTypeCode) :?>
                <option name="<?= $entityTypeCode['name'] ?>" value="<?= $entityTypeCode['value'] ?>">
                    <?= $entityTypeCode['name'] ?>
                </option>
                <?php endforeach; ?>
            </select>
            <label for="attribute-id">Attribute:</label>
            <select id="attribute-id" onchange="attributeValueExtra.getAttributeValueList()">
                <option name=" " value=" " selected="selected"> </option>
            </select>
        </form>
    </div>
<?php endif; ?>
